#!/bin/bash
set -eu

if [ "${DOCKERFILE_PATH:=""}" = "" ]; then
  DOCKERFILE_PATH_ARG=""
else
  DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

IMAGE_NAME=${IMAGE_NAME:=git-use-commit-times}

tar -czh . | docker build ${DOCKERFILE_PATH_ARG} -t ${IMAGE_NAME} -
