#!/bin/bash
set -eu

if [ "$DOCKERFILE_PATH" = "" ]; then
  DOCKERFILE_PATH_ARG=""
else
  DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

if [ "${DOCKER_TAG}" = "latest" ]; then
  docker build ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
else
  docker build --build-arg LIBGIT2_TAG=${DOCKER_TAG} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
fi

