#!/bin/bash
set -eu

if [ ! "${DOCKER_TAG}" = "latest" ]; then
  GIT2GO_VER=
  VERSION_NUMBER=${DOCKER_TAG#v}
  VERSIONS=(${VERSION_NUMBER//./ })
  if [ "${VERSIONS[0]}" = "0" ]; then
    if [ "${VERSIONS[1]}" = "99" ]; then
      GIT2GO_VER=29
    fi
    if [ "${VERSIONS[1]}" = "28" ]; then
      GIT2GO_VER=28
    fi
  fi
  if [ "${VERSIONS[0]}" = "1" ]; then
    if [ "${VERSIONS[1]}" = "0" ]; then
      if [ "${VERSIONS[2]}" = "1" ]; then
        GIT2GO_VER=30
      fi
    else
      GIT2GO_VER=$((30+${VERSIONS[1]}))
    fi
  fi
  if [ -n "${GIT2GO_VER}" ]; then
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:git2go-v${GIT2GO_VER}
    docker push ${DOCKER_REPO}:git2go-v${GIT2GO_VER}
  fi
fi
